### ISSUE TITLE
Test utility hangs indefinitely

### ISSUE THREAD

**Issue by Oleg26Dev** [openlink/iODBC#32]
I test the DSN using test utility. 
After I have selected the DSN the utility hangs up in at call:

```
**SQLDriverConnectW** (hdbc, 0, (SQLWCHAR *) wdataSource, SQL_NTS,
      (SQLWCHAR *) outdsn, NUMTCHAR (outdsn), &buflen, SQL_DRIVER_COMPLETE);
// connect does not completed

  if (status != SQL_SUCCESS)
    ODBC_Errors ("SQLDriverConnectW");]


```

How to understand the reason why it does not respond and does not connect?
Another application (the famous application Tableau) works with this DSN ok.

**Comment by TallTed** [comment]
There are many unanswered questions in this report...
* What "test utility" are you using?
* On what platform are you testing?
* What driver are you testing?
* Can we see the definition of the DSN being tested?
* Can we see an ODBC trace showing the "test utility" connection failure?  Can we also see a trace showing Tableau connect successfully?

**Comment by Oleg26Dev** [comment]
I am using Mac OS X Sierra (10.13).
I have installed the iODBC and use the test utility which iODBC contains, by fact it is the 

[https://github.com/openlink/iODBC/blob/develop/samples/iodbctest.c](url)

I am trying only to test my odbc driver. I see that Tableau works fine with this driver but the iodbctest hangs on call SQLDriverConnectW. I'd like to know what and how can I debug to understand why it hangs. And how to understand: is it driver hanging or app?
What can I do in this situation?

**Comment by timhaynesopenlink** [comment]
Hi,

There are quite a few reasons why a connection might hang. Irksomely `SQLDriverConnectW()` is the point where control transitions from the driver manager into the ODBC driver; all sorts of things could be happening. Here's a few things to consider:

*  what command exactly are you executing? Does it have a valid connect string on the end, *not* just a DSN?  (see e.g. `iodbctest "DSN=dsn;UID=me;PWD=secret"`)
* environment variables: have you exported ODBCINI to point to a valid odbc.ini file? In which odbc.ini files on your system have you defined the DSN? (see `locate odbc.ini`)
* Networking issues: can you ping the server whose IP address you've used in the odbc.ini file? By name? By IP#? Does it make a difference if you use a DNS name in the odbc.ini as distinct from the IP address? If you `telnet ip_address 35001`, does it connect?
* bit-ness: life is easiest if your application, iODBC and your driver are *all* 32-bit xor *all* 64-bit. It must be true with tableau; is iodbctest compiled with the same architecture? (Use `file iodbctest` to check.)
* incomplete login information: depending on the driver, if it needs to prompt for login information (e.g. it doesn't recognize the "UID" and "PWD" keywords in the DSN), there could be problems with the driver trying to pop-up a dialog in an environment that doesn't support such (terminal; X11 with no DISPLAY available).

Finally, after checking all the above, one way to debug this thing would be to run dtruss. In one terminal window, run `dtruss -W iodbctest 2>&1 | tee truss.log`  ; then in another, run your `iodbctest` command. Hopefully the dtruss window will show mentions of libraries loaded and files opened and the last few syscalls should show where it's hanging.

HTH

~Tim

**Comment by Oleg26Dev** [comment]
Thank you very much for the detail answer, I will do all what you advised!

**Comment by TallTed** [comment]
@Oleg26Dev - 

Please also confirm whether you have installed [the latest iODBC SDK, which includes pre-built libraries and executables](http://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads#Mac%20OS%20X), or built iODBC yourself.

If you installed the SDK, your configuration including DSNs should definitely be in the standard locations (System `/Library/ODBC/` and User `/Users/*/Library/ODBC/`), and all installed iODBC libraries and apps will be "fat binaries" which include both 32-bit and 64-bit support.  The iODBC apps will run as 64-bit by default; you can use the Finder's **Get Info** dialog to change that, for testing or for use with any 32-bit only drivers.

We would recommend that you likewise build your ODBC driver as a fat binary, so that both 32-bit and 64-bit apps can connect through it.

**Comment by win32nipuh** [comment]
@TallTed  thank you, could you please give me any links how to build my odbc driver as a "fat binaries" ?
and how then work with 32 and 64 bit versions?
Now I build separately the 32-bit and 64-bit drivers and provide them to customers.

**Comment by TallTed** [comment]
@win32nipuh - 

I think [this article on Apple's site](https://developer.apple.com/library/archive/documentation/Porting/Conceptual/PortingUnix/compiling/compiling.html) is probably what you need for building fat a/k/a universal binaries.  

Current macOS is only x86-based architectures, and fat binaries typically include compilation 32-bit `-arch i386` and 64-bit `-arch x86_64`.  (Past flavors of fat binaries have included compilation for 32-bit and 64-bit PPC, or for 32-bit 68k and 32-bit PPC, or for 32-bit PPC and 32-bit x86, or even for for 32-bit PPC and 64-bit PPC and 32-bit x86 and 64-bit x86_64.)

**Comment by win32nipuh** [comment]
@TallTed
It seems the freshest Mac OS X Mojave supports 64-bit dylib building only. I edited my build scripts.

**Comment by traceon** [comment]
I am currently debugging some issue in a custom driver and came across somewhat related/similar behavior.

In my case, `iodbctest` and `iodbctestw` just exit with `Have a nice day.` right after starting when provided a DSN with an ANSI driver (Unicode version of the same driver works fine). After building iodbc manually and adding debug printout here and there, it turned out that at... https://github.com/openlink/iODBC/blob/d9293505804e775488582321420e427464e6c3ce/samples/iodbctest.c#L327
...the value of `status` variable is `2` in my case, which corresponds to `SQL_STILL_EXECUTING` - a very surprising value to meet. However, when I just copy-pasted `iodbctest` code into the driver project's infrastructure (in order to run and debug it from within Xcode -- attaching to the `iodbctest` doesn't work, it exits immediately with `Have a nice day.`), I noticed that it actually hangs in `SQLDriverConnect()` at:
https://github.com/openlink/iODBC/blob/d9293505804e775488582321420e427464e6c3ce/samples/iodbctest.c#L321

...and the stack trace looks like a deadlock (I didn't dig any further, but assume that this is somehow detected as an incomplete async operation by the driver manager in other environment probably?):

```
#0	0x00007fff63774f9a in __psynch_mutexwait ()
#1	0x0000000100765407 in _pthread_mutex_firstfit_lock_wait ()
#2	0x0000000100762fce in _pthread_mutex_firstfit_lock_slow ()
#3	0x0000000100652254 in SQLSetConnectOption at /tmp/iODBC/iodbc/hdbc.c:711
#4	0x000000010064321b in _iodbcdm_SetConnectOption_init at /tmp/iODBC/iodbc/connect.c:298
#5	0x000000010064457c in _iodbcdm_driverload at /tmp/iODBC/iodbc/connect.c:1345
#6	0x000000010064749b in SQLDriverConnect_Internal at /tmp/iODBC/iodbc/connect.c:2747
#7	0x000000010064926f in SQLDriverConnect at /tmp/iODBC/iodbc/connect.c:2984
#8	0x0000000100004d8b in ODBC_Connect(char*) at /tmp/custom-odbc-driver/test/misc_it.cpp:374
#9	0x0000000100006343 in main_(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /tmp/custom-odbc-driver/test/misc_it.cpp:1131
...
```
Here `main_` correspond to `iodbctest`'s `main` (slightly modified to accept just a connection string as `std::string` instead of `argc`/`argv`.)

**Comment by traceon** [comment]
In fact, this even looks like some other issue, I came across recently: looks like the driver manager tries to call `SQLSetConnectOption()` of the driver, but ends up calling its own implementation, causing the deadlock. Similar thing happened with me with `SQLBindParameter()`, where the driver also looked the dynamically loaded library of the driver for the obsolete `SQLBindParam()` even though it already found the `SQLBindParameter()`. Problem arose when it actually found `SQLBindParam()`, but that was its own function and that was clearly indicated in the Xcode debugger. Then, the code ended up using `SQLBindParam()` which predictably caused "Invalid handle" error, since the handle passed to iodbc's `SQLBindParam()` was unmasked raw driver's handle. I worked that around by providing own forwarding `SQLBindParam()` implementation, but I think there is something fundamentally wrong either in the assumptions made in iodbc driver manager about how dynamic loader is expected to resolve symbols, or some problem in linkage somewhere in the driver (where I don't see any)? I am writing in hope that this problem looks familiar and you have known guidance on fixing such things (since this looks like a huge problem either in iodbc or in how driver is linked using iodbc).

**Comment by TallTed** [comment]
@smalinin @pkleef @openlink - Please have a look at this.

**Comment by smalinin** [comment]
> In fact, this even looks like some other issue, I came across recently: looks like the driver manager tries to call `SQLSetConnectOption()` of the driver, but ends up calling its own implementation, causing the deadlock. Similar thing happened with me with `SQLBindParameter()`, where the driver also looked the dynamically loaded library of the driver for the obsolete `SQLBindParam()` even though it already found the `SQLBindParameter()`. Problem arose when it actually found `SQLBindParam()`, but that was its own function and that was clearly indicated in the Xcode debugger. Then, the code ended up using `SQLBindParam()` which predictably caused "Invalid handle" error, since the handle passed to iodbc's `SQLBindParam()` was unmasked raw driver's handle.

- The SQLBindParam isn't deprecated => https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/sqlbindparam-mapping?view=sql-server-ver15

- I will recheck loading of ODBC driver on OSX.

- What your driver return for call
  `SQLSetEnvAttr(hdbc, SQL_ATTR_ODBC_VERSION, ....)`

- Executed the command  `$ nm -gU myodbc.so `  for your ODBC driver and sent output log here.
Example:
```
bash-3.2$ nm -gU virtodbc_r.so 
0000000000006be0 T _SQLAllocConnect
0000000000006d00 T _SQLAllocEnv
00000000000020a0 T _SQLAllocHandle
0000000000007000 T _SQLAllocStmt
0000000000007010 T _SQLBindCol
000000000000a100 T _SQLBindParameter
...
```

**Comment by traceon** [comment]
> The SQLBindParam isn't deprecated => https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/sqlbindparam-mapping?view=sql-server-ver15

Kind of, but from the same link:
> An ODBC 3.x driver does not need to implement SQLBindParam.

---

> What your driver return for call
> SQLSetEnvAttr(hdbc, SQL_ATTR_ODBC_VERSION, ....)

`SQL_OV_ODBC3`

---

> Execute the command $ nm -gU myodbc.so for your ODBC driver and sent FULL output log here.

Symbols of the ANSI version of the driver, compiled without optimizations:
https://gist.github.com/traceon/56662d16dd0774f68100003339317300#file-clickhouse-odbc-driver-symbols-L2051-L2113

**Comment by traceon** [comment]
> I will recheck loading of ODBC driver on OSX.

So far, it is observed when the ANSI driver is used with `iodbctest` or `iodbctestw` in macOS, and also in Ubuntu, but only with `iodbctest` (however I haven't verified that it is the exact same problem in Linux.)

**Comment by smalinin** [comment]
> > What your driver return for call
> > SQLSetEnvAttr(hdbc, SQL_ATTR_ODBC_VERSION, ....)
> 
> `SQL_OV_ODBC3`

It could not return `SQL_OV_ODBC3`, it must return SQL_ERROR, SQL_SUCCESS or etc.

> Symbols of the ANSI version of the driver, compiled without optimizations:
> https://gist.github.com/traceon/56662d16dd0774f68100003339317300#file-clickhouse-odbc-driver-symbols-L2051-L2113
Looks, less or more ok .

**Comment by traceon** [comment]
> It could not return SQL_OV_ODBC3, it must return SQL_ERROR, SQL_SUCCESS or etc.

Right, sorry, misread your question. It sets `SQL_OV_ODBC3` and returns `SQL_SUCCESS`.

**Comment by traceon** [comment]
When I was debugging, here both `odbc_ver` and `dodbc_ver` had value `3`:
https://github.com/openlink/iODBC/blob/f69576ee643ebe243da23b637ca6f9bd5b96d0b2/iodbc/prepare.c#L640-L642

**Comment by traceon** [comment]
Also, the driver is open-source, so If required, I can provide instructions on how to build and reproduce.

**Comment by smalinin** [comment]
@traceon 
It looks, that something is unproperly in your OSX build.
I changed your driver sources a little for remove SQLSetConnectOption from exported functions.
- checking the binary
```
bash-3.2# nm -gU libclickhouseodbc.dylib | grep SQLSetConnect
0000000000051ac0 T _SQLSetConnectAttr
```
and to check that it doesn't have SQLConnectW
```
bash-3.2# nm -gU libclickhouseodbc.dylib | grep SQLConnect
0000000000002140 T _SQLConnect
```
So test binary is ready for testing.

- iODBC uses OSX function `dlopen` and `dlsym` for load ODBC driver and get proc handle,
so create a simple example
```
#include <stdio.h>
#include <dlfcn.h>
int main() {
 void *dll;
 void *proc;
 dll = dlopen("//Library//ODBC//clickhouse//libclickhouseodbc.dylib", (RTLD_NOW | RTLD_LOCAL));
 fprintf(stderr, "dll = %ld\n", dll);
 if (dll) {
   proc = dlsym(dll, "SQLConnectW");
   fprintf(stderr, "SQLConnectW proc = %ld\n", proc);
   proc = dlsym(dll, "SQLSetConnectAttr");
   fprintf(stderr, "SQLSetConnectAttr proc = %ld\n", proc);
   proc = dlsym(dll, "SQLSetConnectOption");
   fprintf(stderr, "SQLSetConnectOption proc = %ld\n", proc);
 }
}
```

- check our test binary with this example
```
bash-3.2$ cc test.c
bash-3.2$ ./a.out
dll = 140275154438992
SQLConnectW proc = 4562095536
SQLSetConnectAttr proc = 4555025088
SQLSetConnectOption proc = 4562134768
```
so you could see, that `dlsym` found `SQLConnectW` in odbc binary, it must not be found,
because it isn't existed in binary and  this function is for Unicode ODBC driver
and it found `SQLSetConnectOption` in odbc binary, but it also isn't existed in odbc binary


- I executed the same with our ODBC drivers, the test doesn't found `SQLConnectW` and `SQLSetConnectOption` in ODBC binary, if it isn't existed in binary.
Therefore you need to rewise all compile/link options/flags for your ODBC driver,
the problem isn't related with iODBC DM.

**Comment by smalinin** [comment]
@traceon 
Remove linking of your ODBC driver with `iodbc` library (  **-framework iodbc** on OSX ), the same is for Linux.
You could link ODBC driver **ONLY** with  `iodbcinst` library, it must resolve your issues.
p.s.
I removed link with `iodbc` and my test.c program works properly with neww clickhouse-odbc binary.

**Comment by traceon** [comment]
> so you could see, that dlsym found SQLConnectW in odbc binary, it must not be found,
because it isn't existed in binary and this function is for Unicode ODBC driver
and it found SQLSetConnectOption in odbc binary, but it also isn't existed in odbc binary

Right, so iodbc finds these function inside itself, where they are defined. Obviously, the way the driver is linked somehow expose this behavior, but isn't this a problem in how iodbc find symbols, in general? Do you see any suspicious things in linking command?

**Comment by traceon** [comment]
> Remove linking of your ODBC driver with iodbc library ( -framework iodbc on OSX ), the same is for Linux.

Thanks, will try that.

**Comment by smalinin** [comment]
> Right, so iodbc finds these function inside itself, where they are defined. Obviously, the way the driver is linked somehow expose this behavior, but isn't this a problem in how iodbc find symbols, in general?

I wrote already, that iODBC DM uses OSX system functions `dlopen` / `dlsym` for find symbols .

**Comment by traceon** [comment]
I wonder if `lt_dlsym()` behaves differently than `dlsym()` in this regard, which could be a good reason for unixodbc using it (i.e. `libltdl`)... Anyway, thanks for your help, I appreciate it!

**Comment by smalinin** [comment]
@traceon 
Also I think, that you don't need linking ODBC driver with `ltdl` library, if you don't use any special loading of some shared libraries, such libraries are be used by ODBC Driver Managers.

**Comment by smalinin** [comment]
> I wonder if `lt_dlsym()` behaves differently than `dlsym()` in this regard, which could be a good reason for unixodbc using it (i.e. `libltdl`)... Anyway, thanks for your help, I appreciate it!

unixodbc uses `dlsym` for working ODBC drivers, and you also DON"T need link with `odbc` library(from unixodbc) only with `odbcinst`

**Comment by smalinin** [comment]
@traceon Only Application that uses iODBC(unixODBC) is linked with both libraries `odbc` and `odbcinst`

**Comment by traceon** [comment]
> unixodbc uses dlsym for working ODBC drivers

They use `lt_dlsym()` as far as I can tell.

> and you also DON"T need link with odbc library(from unixodbc) only with odbcinst

Yeah, got it.

**Comment by smalinin** [comment]
> > unixodbc uses dlsym for working ODBC drivers
> 
> They use `lt_dlsym()` as far as I can tell.

I think, this just a wrap around OSX system function dlsym

**Comment by traceon** [comment]
Could be, however, similarly linked with unixodbc driver does not exhibit such problems, which may be an indication that actual behavior of `lt_dlsym()` is not the same as `dlsym()`. Or it could be just a bad luck in case of iODBC-linked driver, and `lt_dlsym()` and `dlsym()` are basically same.

**Comment by smalinin** [comment]
- `libltdl` is outdated, last version is from 16-feb-2015 and it is **aplha** release, we need stable release, that supports all OSX features include: frameworks, Cococa and that properly initialized Cocoa frameworks, when it is used by ODBC driver.

- Now your ODBC driver is linked with `iodbc` (that has for example SQLConnectW, SQLSetConnectOption), when ODBC DM load your ODBC driver the `dlopen` resolves all links and load `iodbc` lib to driver space, so for example;  your ANSI driver doesn't have `SQLConnectW` but loaded `iodbc` has this function and iODBC DM will think, that your ANSI ODBC driver is Unicode ODBC driver and the driver behavior will be  unpredictable.
