### ISSUE TITLE
Adding a DSN throws "Request failed" error

### ISSUE THREAD

**Issue by afreedma** [openlink/iODBC#34]
* Using Mojave 10.14.2 (18C54) on a 2018 15" MacBook Pro (2.2GHz i7, 32GB)
* Trying to use Tableau Desktop 2018.1.3 64-bit with Amazon EMR (HiveServer2) with [AmazonHiveODBC_1.1.1.1001](https://s3.amazonaws.com/amazon-odbc-jdbc-drivers/public/AmazonHiveODBC_1.1.1.1001.zip)
* Downloaded [mxkozzzz.dmg](
http://download3.openlinksw.com/uda/components/7.0/universal-apple-macosx10.7-32/mxkozzzz.dmg) which installs iODBC Administrator 3.52.12

1. Launch _iODBC Administrator64_ (same behaviour with the 32-bit version though)
2. Add a _User DSN_ (or a _System DSN_, same behaviour)
3. Select _Amazon Hive ODBC Driver_ and click _Finish_
4. Set a name (I used _Amazon EMR_) and click _Ok_
5. Error message: **An error occurred when trying to add the DSN :** Request failed

<img width="532" alt="image" src="https://user-images.githubusercontent.com/6175363/50718590-51f3d400-10e5-11e9-81b4-0cedfcee1b0f.png">

**Comment by TallTed** [comment]
I have a feeling you're running into a file permissions issue.  Please provide complete output of the following `Terminal.app` command (best to be copied-and-pasted, and run while you're not connected to any network volumes) --

    sudo find / \( -name 'odbc*.ini' -or -name '.odbc*.ini' \) -ls

**Comment by afreedma** [comment]
`sudo find / \( -name 'odbc*.ini' -or -name '.odbc*.ini' \) -ls > odbc_perms.txt`
[odbc_perms.txt](https://github.com/openlink/iODBC/files/2734480/odbc_perms.txt)

**Comment by TallTed** [comment]
OK, please execute these commands to fix the permissions on those config files --

    sudo chown afreedman:staff /Users/afreedman/Library/ODBC/odbc*.ini

    sudo chmod 644 /Users/afreedman/Library/ODBC/odbc*.ini

Due to evolving sandboxing on macOS, you may also need to move the Amazon ODBC driver directories from `/opt/amazon/{hiveodbc,redshift}` to `/Library/ODBC/amazon/{hiveodbc,redshift}`.  Symlinks from the latter to the former *may* suffice.

(For consistency, you may then also want to move the Simba ODBC driver directories from `/Library/simba/{sqlserverodbc,spark}` to `/Library/ODBC/simba/{sqlserverodbc,spark}`, or create similar symlinks.)

After moving the ODBC driver directories, you'll also need to tweak the contents of any `odbc.ini` or `odbcinst.ini` which references their old location.

Please let me know if these adjustments resolve the issue.

**Comment by TallTed** [comment]
I'm sorry; I omitted part of the permissions/ownership fix.

    sudo chown root:admin /Library/ODBC/odbc*.ini

    sudo chmod 664 /Library/ODBC/odbc*.ini

This should resolve the remaining issues with System DSNs.

**Comment by afreedma** [comment]
That resolved it. I can now create System & User DSNs without error.
I used the ownership/permissions changes, but none of the symlinking or file copying.
Thanks!
