### ISSUE TITLE
iODBC administrator 64

### ISSUE THREAD

**Issue by philshil** [openlink/iODBC#51]
Hi,

We have two macbook pros which have this software, both are running macOS catalina. i can open the administrator panel fine but if i want to edit or add a new connection i can open the connection type selection box but then it just closes, almost like it crashes out. 

We do have the odbc.ini file and someone has updated it but it doesn't seem to be working. They can't remember how it looked before hand. The error at the moment is the server doesn't exist.. where it does. Do you have a sample actual sql odbc.ini file?

**Comment by smalinin** [comment]
What kind of ODBC driver did you use? 
Could you attach the screenshoot, when you select the connection type ? The *iODBC administrator* doesn't have such dialog.
Could you attach the crashlog here?
The content of odbc.ini file has ODBC driver dependend settings, so I could give you only an example.
The next is example settings for Virtuoso ODBC driver.
```
[ODBC Data Sources]
Local Virtuoso = OpenLink Virtuoso ODBC Driver

[Local Virtuoso]
Driver             = /Library/ODBC/OpenLink Virtuoso ODBC Driver.bundle/Contents/MacOS/virtodbc_r.so
Address            = localhost:1111
PWDClearText       = 0
LastUser           = dba
DayLight           = Yes
RoundRobin         = No
NoSystemTables     = No
TreatViewsAsTables = No
WideAsUTF16        = No

```

**Comment by philshil** [comment]
Hi @smalinin 
Thanks for getting back to me. It's the SQL one. See screenshots (system DSN and the box to select ODBC driver) If i click finish on the choose ODBC driver it just closes and nothing else comes up. The same if i click edit nothing comes up. Might sound silly, but where will i find the crashlog specific to this? 
<img width="667" alt="Screenshot 2020-05-29 at 08 15 43" src="https://user-images.githubusercontent.com/12427777/83232510-35968280-a185-11ea-8457-58d60b6aeb95.png">
<img width="733" alt="Screenshot 2020-05-29 at 08 15 36" src="https://user-images.githubusercontent.com/12427777/83232520-38917300-a185-11ea-86bf-43c58a0244a4.png">

**Comment by smalinin** [comment]
What kind of version iODBC did you use? (It is in the **About** tab)

Install the latest iODBC from http://download3.openlinksw.com/uda/components/8.0/universal-apple-macosx10.7-32/mxkozzzz.dmg  it is latest iODBC 3.52.14

I checked Actual ODBC on Mojave and Catalania OS, the latest iODBC work properly on that OS.
If you add new DSN to to **SystemDSN** with **iODBC Administrator64**, everything works fine.
BUT if you try to add new DSN to **UserDSN**, nothing is happened(without crash).
The Actual ODBC drivers linked with /usr/lib/iodbcinst.dylib library(it is OSX libs, we don't support it)  instead of using /Library/iODBCinst.framework and something doesn't work properly, when Actual ODBC drivers are used  with **UserDSN** (you must resolve it with Actual deveopers, if you want fix it).

 Also you could use Actual ODBC manager app from /Application/Utilities/ODBC manager.

**Comment by philshil** [comment]
It is 3.52.14 already installed. I tried to add the SQL DSN in SystemDSN and when i select it and press finish it just does nothing and goes back to the sources list, just as you describe with UserDSN. 

I can't load the ODBC manager from utilities as it says it needs updating to work with this version of macOS. I'm running 10.15.4

When trying to use the connection that is already existing (which is the one i'm trying to update)i get the error saying server is incorrect. Can i paste the odbc.ini file here to check?

**Comment by smalinin** [comment]
Reinstall iODBC from http://download3.openlinksw.com/uda/components/8.0/universal-apple-macosx10.7-32/mxkozzzz.dmg , if it has build date before 12-feb-2020, checked in About tab.

 Also note that I used Actual ODBC manager ver 1.0.19  from 19-may-2020.
Both worked for me on OSX 10.15.2
 
I have updated OSX to 10.15.5 and both Actual ODBC manager and **iODBC administrator64** works also, so try download latest Actual ODBC installer and reinstall it.

Also I note, that if I add new DSN on **UserDSN** in **iODBC administrator64** it is added to **SystemDSN** instead of **UserDSN** 
You could paste your odbc.ini, but I am not sure, that I could help you, this question must be addressed to Actual ODBC support.

**Comment by smalinin** [comment]
My odbc.ini for Actual ODBC for SQLServer looks:
```
[ODBC Data Sources]
ActualSQL      = Actual SQL Server


[ActualSQL]
Driver              = /Library/ODBC/Actual SQL Server.bundle/Contents/MacOS/atsqlsrv.so
Description         = 
Server              = 192.168.100.149
Database            = pubs
ASA Database        = 
Language            = 
UserID              = 
UseKeychain         = 
Trusted_Connection  = 
QuotedId            = 
AnsiNPW             = 
IncludeViews        = 
ForceLongParameters = 
AutoDetectEncoding  = 
WideAPI             = 
UnicodeTextTypes    = 
MultiByteEncoding   = 
ServerName          = ActualSQL
host                = 192.168.100.149
client charset      = UTF-8
QueryLog_On         = 
QueryLogTime        = 
QueryLogFile        = 
Regional            = 
StatsLog_On         = 
StatsLogFile        = 
Address             = 
Port                = 1433
DynamicPort         = 
UseNTLMv2           = 
AutoReconnect       = 
ApplicationIntent   = 
Encryption          = 
TDS_Version         = auto
TextSize            = 
PacketSize          = 

```

**Comment by philshil** [comment]
Hi @smalinin,

i still can't get it to work at the moment. I can't even add a new DSN. it just loads nothing and goes back to the iODBCAdministrator64 main screen.
